gesdinet_jwt_refresh_token:
  user_provider: security.user.concrete.app_user_provider
  refresh_token_class: App\Entity\RefreshToken
  ttl: 2592000
  cookie:
    enabled: true
    same_site: none # default value
    path: / # default value
    # domain: .netlify.app # default value
    http_only: true # default value
    secure: true # default value
    remove_token_from_body: true # def
