<?php

// This file was generated by running "composer dump-env prod"

return array(
  'APP_ENV' => 'prod',
  'APP_SECRET' => '7415b288cbd18dfee6c1b69e8b53c6ad',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '',
  'MERCURE_URL' => '	https://n1f0rt.stackhero-network.com/.well-known/mercure',
  'MERCURE_PUBLIC_URL' => '	https://n1f0rt.stackhero-network.com/.well-known/mercure',
  'MERCURE_JWT_SECRET' => '!ChangeMenfsdnfosdSDFSDfojfnze56448949sdfsdfZEFzepklf54984!',
  'MAILER_DSN' => 'gmail://hugo.latreille%40gmail.com:tcqafasbdqylnwdr@default',
  'DATABASE_URL' => 'postgresql://quasiquiz:quasiquiz@localhost:5432/quasiquiz?serverVersion=15&charset=utf8',
  'JWT_SECRET' => '56465DSfsdsdfZEfze5489Asdkjroze',
);